package Components.Cards.Collection;

import Components.Utilities.CustomScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JScrollBar;

public class RecentlyAddedContainer extends javax.swing.JPanel {

    /**
     * Creates new form RecentlyAddedContainer
     */
    public RecentlyAddedContainer() {
        initComponents();
        customizeScrollBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER,
                                                 javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        setBackground(new java.awt.Color(232, 235, 242));
        setFont(new java.awt.Font("DM Sans", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        jLabel1.setText("Recently Added");

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

    }// </editor-fold>

    private void customizeScrollBar() {
        // Get the horizontal scroll bar
        JScrollBar horizontalScrollBar = jScrollPane1.getHorizontalScrollBar();
        CustomScrollBar.customizeScrollBar(horizontalScrollBar);
        
        // Update the scroll pane
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration

    public javax.swing.JScrollPane getScrollPane() {
        return jScrollPane1;
    }
}
