package Components.Cards.Collection;

import Components.Utilities.CustomScrollBar;
import Components.Utilities.ImageResizer;

import javax.swing.ImageIcon;
import javax.swing.JScrollBar;
import java.net.MalformedURLException;
import java.net.URL;

public class RecentlyAddedCard extends javax.swing.JPanel {

    /**
     * Creates new form RecentlyAddedCard
     */

    public RecentlyAddedCard(String headingText, String imageLink, String description, String dateAdded) {
        initComponents();
        customizeScrollBar();
        setHeadingText(headingText);
        setSnippetImage(imageLink);
        setDescription(description); 
        setDateAdded(dateAdded);
    }

    private void customizeScrollBar() {
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
        CustomScrollBar.customizeScrollBar(verticalScrollBar);
        
        // Update the scroll pane
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        SnippetImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        dateAdded = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("DM Sans", 0, 10)); // NOI18N

        jLabel2.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        jLabel2.setText("Item Name");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("DM Sans", 0, 10)); // NOI18N
        jTextPane1.setText("Description");
        jScrollPane1.setViewportView(jTextPane1);

        dateAdded.setFont(new java.awt.Font("DM Sans", 0, 10)); // NOI18N
        dateAdded.setForeground(new java.awt.Color(100, 100, 100));
        dateAdded.setText("Added on date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(SnippetImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(dateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 78, Short.MAX_VALUE)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(SnippetImage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateAdded)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel SnippetImage;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel dateAdded;
    // End of variables declaration

    public void setHeadingText(String headingText){
        jLabel2.setText(headingText);
    }

    public void setDateAdded(String date){
        dateAdded.setText(date);
    }
    
    public void setSnippetImage(String url){
        final int IMAGE_WIDTH = 185;
        final int IMAGE_HEIGHT = 105;

        try{
            URL imageURL = new URL(url);
            ImageResizer resize = new ImageResizer();
            ImageIcon scaledIcon = resize.toCover(imageURL, IMAGE_WIDTH, IMAGE_HEIGHT);
            SnippetImage.setIcon(scaledIcon);
            if (SnippetImage.getParent() != null){
                SnippetImage.getParent().revalidate();
                SnippetImage.getParent().repaint();
            }

        } catch (MalformedURLException e){
            System.err.println("Invalid URL");
            e.printStackTrace();
        }
    }

    public void setDescription(String descriptionText){
        jTextPane1.setBorder(null);
        jTextPane1.setText(descriptionText);
    }
}
